
---
- name: Run command play
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Wait until application is healthy
      ansible.builtin.uri:
        url: http://localhost:8080/health
        return_content: true
      register: app_health
      retries: 5
      delay: 10
      until: app_health.status == 200